---

- name: preflight | include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: preflight | define additional_packages
  set_fact:
    additional_packages: "{{ __additional_packages | list }}"
  when: additional_packages is not defined
